product_list:
  path: /api/v1/products
  controller: App\Controller\ProductController::index
  methods: [GET]

product_create:
  path: /api/v1/products
  controller: App\Controller\ProductController::create
  methods: [POST]